[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
build = "0.0.2"
lambda_runtime = "0.7.3"
serde_json = "1.0.91"
tokio = "1.24.2"
